### ISSUE TITLE
ANOTHER ISSUE

### ISSUE THREAD

**Issue by i34i1hjk** [stairman06/minecraft-manager#6] opened 2019-06-17 16:42 UTC
exporting on mac is completely broken as it just hangs on this
![Screen Shot 14](https://user-images.githubusercontent.com/50601488/59621430-e6cb1680-90f4-11e9-824e-49d21bded8e1.png)

**Comment by stairman06** [comment] 2019-06-17 16:52
Duplicate of #5

**Closed by stairman06** 2019-06-17 16:52 UTC

**Comment by i34i1hjk** [comment] 2019-06-17 17:14
bruuuuuuh
